# Generated by Django 5.2.13 on 2026-07-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family", models.CharField(max_length=50)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("crawler", "Crawler"),
                            ("assistant", "Assistant"),
                            ("script", "Script"),
                            ("probe", "Probe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("path", models.CharField(max_length=512)),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("probe", models.BooleanField(default=False)),
                ("authenticated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="agents_agen_created_4b366f_idx"
                    ),
                    models.Index(
                        fields=["family", "created_at"],
                        name="agents_agen_family_f2f5e3_idx",
                    ),
                ],
            },
        ),
    ]
