# Generated by Django 5.1.14 on 2025-12-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(max_length=16)),
                ('category', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=32)),
                ('postal_code', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=32)),
                ('cohort', models.DateField(help_text='Identified year+month cohort. Day always 1.')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(help_text='Date of registration in CCN Bikes')),
                ('identity', models.IntegerField(help_text='Registration identity provided by CCN Bikes')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=16)),
                ('date_of_birth', models.DateField()),
                ('category', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=32)),
                ('postal_code', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=32)),
                ('member_for', models.CharField(help_text='Self-reported membership length', max_length=16)),
            ],
        ),
    ]
