# Generated by Django 5.1.14 on 2025-12-20 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='member_for',
        ),
        migrations.AddField(
            model_name='registration',
            name='duration',
            field=models.CharField(default='', help_text='Self-reported membership duration', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Linked to member record', null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.member'),
        ),
    ]
