# Generated by Django 5.1.14 on 2025-12-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_registration_created_at_registration_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='city',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
