# Generated by Django 5.1.14 on 2025-12-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_registration_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.CharField(max_length=64),
        ),
    ]
