# Generated by Django 5.1.14 on 2025-12-21 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_alter_registration_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=128)),
                ('confidence', models.FloatField(help_text='Confidence score between 0..1')),
                ('matched_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.registration')),
            ],
        ),
    ]
