# Generated by Django 5.1.14 on 2025-12-21 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='member',
        ),
    ]
