# Generated by Django 5.1.14 on 2025-12-21 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_remove_registration_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='membership.registration'),
        ),
    ]
