# Generated by Django 5.1.14 on 2025-12-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_alter_match_registration_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'match', 'verbose_name_plural': 'matches'},
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(default='', max_length=64),
        ),
    ]
