# Generated by Django 5.1.14 on 2025-12-21 04:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_add_member_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='year',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
