# Generated by Django 5.1.14 on 2025-12-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_registration_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=False, help_text='Identifies the member as active or not based on if they have a registration from the current year'),
            preserve_default=False,
        ),
    ]
