# Generated by Django 5.1.14 on 2025-12-21 05:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_member_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='active',
        ),
        migrations.AddField(
            model_name='member',
            name='last_registration_year',
            field=models.DateField(default=django.utils.timezone.now, help_text='Identifies which year the member was last registered. Month and day always 1.'),
            preserve_default=False,
        ),
    ]
