# Generated by Django 5.1.6 on 2025-02-26 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_program_event_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_virtual',
            new_name='virtual',
        ),
    ]
