# Generated by Django 5.1.6 on 2025-02-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_rename_is_virtual_event_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
