# Generated by Django 5.1.6 on 2025-02-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_ride_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='point_of_departure',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
