# Generated by Django 5.1.6 on 2025-02-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_alter_registration_speed_range_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_emergency_contact',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='registration',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
