# Generated by Django 5.1.6 on 2025-02-26 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_event_requires_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speedrange',
            options={'ordering': ['lower_limit']},
        ),
    ]
