# Generated by Django 5.1.6 on 2025-02-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_alter_speedrange_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='ride_leader_preference',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('na', 'N/A')], default='na', max_length=2),
        ),
    ]
