# Generated by Django 5.1.6 on 2025-03-22 22:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0011_alter_registration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_closes_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
