# Generated by Django 5.1.6 on 2025-03-22 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0012_event_registration_closes_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backoffice.program'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backoffice.event'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backoffice.ride'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='speed_range_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backoffice.speedrange'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backoffice.route'),
        ),
    ]
