# Generated by Django 5.1.6 on 2025-03-22 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0013_alter_event_program_alter_registration_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
