# Generated by Django 5.1.6 on 2025-04-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0016_registration_cancelled_at_registration_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_url',
            field=models.URLField(blank=True, help_text='If provided, users will get a link to the location. Typically, you can place a Google Maps location here.', verbose_name='Location URL'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(default='', help_text='Enter the external registration link if any. If no link is provided, RideHub will manage registrations.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Description of the event to share with members.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Can a physical or virtual location.', max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_closes_at',
            field=models.DateTimeField(help_text='Closing time of the registration'),
        ),
        migrations.AlterField(
            model_name='event',
            name='requires_emergency_contact',
            field=models.BooleanField(default=True, help_text='Check if you require registrations to provide emergency contact details.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ride_leaders_wanted',
            field=models.BooleanField(default=True, help_text='Check if you want to allow members to sign up as ride leaders.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(help_text='Start time of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='virtual',
            field=models.BooleanField(default=False, help_text='Mark virtual if it happens online, via Teams, Zwift or other electronic means.'),
        ),
    ]
