# Generated by Django 5.1.6 on 2025-04-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0017_event_location_url_event_registration_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Physical (e.g. "Andrew Haydon Park") or virtual location ("Teams").', max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, help_text='Enter the external registration link if any. If no link is provided, RideHub will manage registrations.'),
        ),
    ]
