# Generated by Django 5.1.6 on 2025-04-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0018_alter_event_location_alter_event_registration_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='name',
            field=models.CharField(help_text='Ride name, for example "A Ride Long"', max_length=128),
        ),
    ]
