# Generated by Django 5.1.6 on 2025-04-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0019_alter_ride_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration_link',
        ),
        migrations.AddField(
            model_name='event',
            name='external_registration_url',
            field=models.URLField(blank=True, help_text='Enter the external registration URL if any. If no URL is provided, RideHub will manage registrations.'),
        ),
    ]
