# Generated by Django 5.1.6 on 2025-04-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0020_remove_event_registration_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_registration_url',
            field=models.URLField(blank=True, help_text='When an external registration URL is provided, registration will be delegated to the external system'),
        ),
    ]
