# Generated by Django 5.1.6 on 2025-04-30 01:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0021_alter_event_external_registration_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='cancelled_at',
            new_name='withdrawn_at',
        ),
        migrations.AddField(
            model_name='registration',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
