# Generated by Django 5.1.6 on 2025-04-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0022_rename_cancelled_at_registration_withdrawn_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registered_at',
        ),
    ]
