# Generated by Django 5.1.6 on 2025-05-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0023_remove_registration_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation.'),
        ),
        migrations.AddField(
            model_name='event',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the event was cancelled.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Indicates if the event has been cancelled.'),
        ),
    ]
