# Generated by Django 5.1.6 on 2025-05-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0024_event_cancellation_reason_event_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='archived',
            field=models.BooleanField(default=False, help_text='Indicates if the event has been archived. Archived events are not visible to members.'),
        ),
        migrations.AddField(
            model_name='event',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the event was archived.', null=True),
        ),
    ]
