# Generated by Django 5.1.6 on 2025-05-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0025_event_archived_event_archived_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_cancelled',
            new_name='cancelled',
        ),
    ]
