# Generated by Django 5.1.6 on 2025-05-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0026_rename_is_cancelled_event_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=1, help_text='Duration of the event in hours.'),
        ),
    ]
