# Generated by Django 5.1.6 on 2025-05-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0027_event_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Duration of the event in hours.'),
        ),
    ]
