# Generated by Django 5.1.6 on 2025-05-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0028_alter_event_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='ride',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
