# Generated by Django 5.1.6 on 2025-05-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0029_alter_ride_options_ride_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of registrations allowed. Blank means no limit. Zero means no registration.', null=True),
        ),
    ]
