# Generated by Django 5.1.6 on 2025-05-12 03:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0031_route_distance_route_elevation_gain_alter_route_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='last_imported_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this route was last imported into the backoffice.'),
        ),
    ]
