# Generated by Django 5.1.6 on 2025-05-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0032_route_last_imported_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='last_imported_at',
            field=models.DateTimeField(blank=True, help_text='When this route was last imported into the backoffice.', null=True),
        ),
    ]
