# Generated by Django 5.1.6 on 2025-05-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0034_alter_route_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
    ]
