# Generated by Django 5.1.6 on 2025-05-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0035_alter_program_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AddField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='End time of the event', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_email',
            field=models.EmailField(blank=True, help_text='When set, members will be able to reach out to the organizer at this email.', max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='visible',
            field=models.BooleanField(default=True, help_text='Check if the event is visible to members.'),
        ),
    ]
