# Generated by Django 5.1.6 on 2025-05-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0036_remove_event_duration_event_ends_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='End time of the event. If left blank, event duration is assumed to be one hour.', null=True),
        ),
    ]
