# Generated by Django 5.1.6 on 2025-06-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0038_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.TextField(help_text='Body of the announcement. Keep formatting to a minimum as there is limited space on the page.'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(help_text='Name of the announcement. Will precede the body of the announcement.', max_length=128),
        ),
    ]
