# Generated by Django 5.1.6 on 2025-06-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0039_alter_announcement_text_alter_announcement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('i', 'Information'), ('w', 'Warning')], default='i', help_text='Type of the announcement. Use warning to get more attention.', max_length=1),
        ),
    ]
