# Generated by Django 5.1.6 on 2025-06-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0043_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_membership',
            field=models.BooleanField(default=True, help_text='If checked, registration cannot complete under user has indicated they are a member.'),
        ),
    ]
