# Generated by Django 5.1.6 on 2025-06-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0044_event_requires_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='requires_membership',
            field=models.BooleanField(default=True, help_text='Check if you want to require users to confirm that they are members.'),
        ),
    ]
