# Generated by Django 5.1.6 on 2025-07-07 01:33

from django.db import migrations


def ensure_user_profiles(apps, schema_editor):
    """
    Ensure all existing users have profiles.
    This runs automatically during deployment migrations.
    """
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('backoffice', 'UserProfile')
    
    users_without_profiles = []
    for user in User.objects.all():
        if not UserProfile.objects.filter(user=user).exists():
            users_without_profiles.append(user)
    
    # Create profiles for users that don't have them
    created_count = 0
    for user in users_without_profiles:
        UserProfile.objects.create(user=user)
        created_count += 1
    
    if created_count > 0:
        print(f"Data migration: Created {created_count} user profiles")


def reverse_ensure_user_profiles(apps, schema_editor):
    """
    Reverse migration - usually not needed for this type of operation.
    We don't want to delete profiles when rolling back.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0045_alter_event_requires_membership'),
        ('auth', '0012_alter_user_first_name_max_length'),  # Ensure auth migrations are applied
    ]

    operations = [
        migrations.RunPython(ensure_user_profiles, reverse_ensure_user_profiles),
    ]
