# Generated by Django 5.1.6 on 2025-11-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0046_ensure_user_profiles_on_deploy'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='legacy',
            field=models.BooleanField(default=False, help_text='Indicates that this is a legacy event imported from WebScorer'),
        ),
        migrations.AddField(
            model_name='event',
            name='legacy_event_id',
            field=models.CharField(blank=True, help_text='Original WebScorer event ID for legacy imports', max_length=32),
        ),
        migrations.AddField(
            model_name='registration',
            name='legacy',
            field=models.BooleanField(default=False, help_text='Indicates that this is a legacy event imported from WebScorer'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='legacy',
            field=models.BooleanField(default=False, help_text='Indicates that this is a legacy profile imported from WebScorer'),
        ),
    ]
