# Generated by Django 5.1.6 on 2025-11-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0047_event_legacy_event_legacy_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='legacy_registration_id',
            field=models.CharField(blank=True, help_text='Original WebScorer registration identifier for legacy imports', max_length=255),
        ),
    ]
