# Generated by Django 5.1.6 on 2025-11-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0048_registration_legacy_registration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender_identity',
            field=models.CharField(choices=[('wm', 'woman'), ('mn', 'man'), ('nb', 'non-binary'), ('ts', 'two-spirit'), ('pn', 'prefer not to say'), ('np', 'not provided')], default='np', max_length=2),
        ),
        migrations.AlterField(
            model_name='registration',
            name='legacy_registration_id',
            field=models.CharField(blank=True, help_text='Generated legacy identifier based on event ID, email and registration timestamp', max_length=255),
        ),
    ]
