# Generated by Django 5.1.6 on 2025-11-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0049_userprofile_gender_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='self_described_gender_identity',
            field=models.CharField(blank=True, help_text='Self-described gender identity', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender_identity',
            field=models.CharField(choices=[('wm', 'woman'), ('mn', 'man'), ('pn', 'prefer not to say'), ('sd', 'self-described'), ('np', 'not provided')], default='np', max_length=2),
        ),
    ]
