# Generated by Django 5.1.14 on 2025-11-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0050_userprofile_self_described_gender_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_authenticated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='legacy',
            field=models.BooleanField(default=False, help_text='Indicates that this is a legacy registration imported from WebScorer'),
        ),
    ]
