# Generated by Django 5.1.14 on 2025-11-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0051_registration_ip_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='is_authenticated',
            new_name='authenticated',
        ),
    ]
