# Generated by Django 5.1.14 on 2025-12-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0052_rename_is_authenticated_to_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_closes_at',
            field=models.DateTimeField(blank=True, help_text='Closing time of the registration. May be blank if an external registration URL is provided.', null=True),
        ),
    ]
