# Generated by Django 5.1.14 on 2025-12-13 22:15

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0053_optional_registration_closes_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', help_text='Optional color to associate with the program', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='program',
            name='emoji',
            field=models.CharField(blank=True, help_text='Optional emoji to make the program name more playful in various settings', max_length=3),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(help_text='Name of the program', max_length=128),
        ),
    ]
