# Generated by Django 5.1.14 on 2025-12-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0054_program_color_program_emoji_alter_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='archived',
            field=models.BooleanField(default=False, help_text='Indicates if this program is archived and not to be used anymore'),
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, help_text='Optional description of the program', max_length=256),
        ),
    ]
