# Generated by Django 5.1.14 on 2025-12-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0055_program_archived_program_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
