# Generated by Django 5.1.14 on 2026-01-17 01:01

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0059_populate_event_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='state',
            field=django_fsm.FSMField(choices=[('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('withdrawn', 'Withdrawn')], default='submitted', help_text='Current state of the registration in the lifecycle.', max_length=50, protected=True),
        ),
    ]
