# Generated by Django 5.2.10 on 2026-03-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0065_usermembershipnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembershipnumber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
