# Generated by Django 5.2.10 on 2026-03-22 02:01

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0068_normalize_phone_numbers_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('announced', 'Announced'), ('live', 'Live'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='live', help_text='Draft: not visible to public. Announced: visible but registration closed. Live: visible with registration open.', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='state',
            field=django_fsm.FSMField(choices=[('submitted', 'Submitted'), ('unverified', 'Unverified'), ('confirmed', 'Confirmed'), ('withdrawn', 'Withdrawn')], default='submitted', help_text='Current state of the registration in the lifecycle.', max_length=50, protected=True),
        ),
    ]
