# Generated by Django 5.2.10 on 2026-03-22 02:01

from django.db import migrations


def mark_existing_verified(apps, schema_editor):
    UserProfile = apps.get_model('backoffice', 'UserProfile')
    UserProfile.objects.filter(
        user__last_login__isnull=False
    ).update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0069_add_email_verification'),
    ]

    operations = [
        migrations.RunPython(mark_existing_verified, migrations.RunPython.noop),
    ]
