# Generated by Django 5.2.10 on 2026-05-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0074_event_all_day_event_registration_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=False, help_text='Mark as all day if event spans multiple days. Start/end times will be ignored.'),
        ),
    ]
