# Generated by Django 5.2.10 on 2026-05-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0075_alter_event_all_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ask_first_time_attendee",
            field=models.BooleanField(
                default=False,
                help_text="Check if you want to ask registrants whether they are new to this type of event.",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="first_time_attendee",
            field=models.CharField(
                choices=[("y", "Yes"), ("n", "No"), ("na", "N/A")],
                default="na",
                max_length=2,
            ),
        ),
    ]
