# Generated by Django 5.2.10 on 2026-05-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0076_add_first_time_signup_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="article",
            field=models.CharField(
                choices=[("a", "a"), ("an", "an")],
                default="a",
                help_text='Indefinite article to use before the program name in sentences (e.g. "a Coffee Club event", "an OBC Tour event").',
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="ask_first_time_attendee",
            field=models.BooleanField(
                default=False,
                help_text="Check if you want to ask registrants whether this is their first time attending an event from this program.",
            ),
        ),
    ]
