# Generated by Django 5.2.10 on 2026-07-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0077_program_article_alter_event_ask_first_time_attendee"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="name_visibility",
            field=models.CharField(
                choices=[
                    ("pb", "Always"),
                    ("ou", "Only to signed-in users"),
                    ("rq", "Only to ride leaders and ride administrators"),
                ],
                default="pb",
                max_length=2,
            ),
        ),
    ]
