# Generated by Django 5.2.10 on 2026-07-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0078_userprofile_name_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="name_visibility",
            field=models.CharField(
                choices=[
                    ("pb", "Everyone"),
                    ("ou", "Only signed-in users"),
                    ("rq", "Only ride leaders and ride administrators"),
                ],
                default="pb",
                max_length=2,
            ),
        ),
    ]
