# Generated by Django 5.2.13 on 2026-07-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0079_alter_userprofile_name_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
