# Generated by Django 5.2.13 on 2026-07-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0080_userprofile_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="audience",
            field=models.CharField(
                choices=[
                    ("e", "Everyone"),
                    ("s", "Only signed in"),
                    ("a", "Only anonymous"),
                ],
                default="e",
                help_text="Which users should see this announcement.",
                max_length=1,
            ),
        ),
    ]
