# Generated by Django 5.2.13 on 2026-07-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0081_announcement_audience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Latitude of the forecast location.",
                        max_digits=8,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Longitude of the forecast location.",
                        max_digits=8,
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        help_text="Hour the forecast applies to, always at the top of the hour."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this forecast was last fetched from the weather provider.",
                    ),
                ),
                (
                    "precipitation",
                    models.CharField(
                        choices=[
                            ("sun", "Sun"),
                            ("cloud", "Cloud"),
                            ("rain", "Rain"),
                            ("thunder", "Thunder"),
                        ],
                        help_text="Precipitation category at the forecast hour.",
                        max_length=8,
                    ),
                ),
                (
                    "temperature_min",
                    models.IntegerField(
                        help_text="Minimum temperature in Celsius for the forecast day."
                    ),
                ),
                (
                    "temperature_max",
                    models.IntegerField(
                        help_text="Maximum temperature in Celsius for the forecast day."
                    ),
                ),
                (
                    "aqi",
                    models.PositiveIntegerField(
                        help_text="US Air Quality Index at the forecast hour."
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude", "time"],
                        name="backoffice__latitud_95ef8c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("latitude", "longitude", "time"),
                        name="unique_forecast_location_time",
                    )
                ],
            },
        ),
    ]
