# Generated by Django 5.2.13 on 2026-07-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0086_forecast_immutable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forecast",
            name="aqhi_max",
        ),
        migrations.RemoveField(
            model_name="forecast",
            name="aqhi_min",
        ),
        migrations.RemoveField(
            model_name="forecast",
            name="conditions",
        ),
        migrations.RemoveField(
            model_name="forecast",
            name="temperature_max",
        ),
        migrations.RemoveField(
            model_name="forecast",
            name="temperature_min",
        ),
        migrations.AddField(
            model_name="forecast",
            name="hourly",
            field=models.JSONField(
                default=list,
                help_text="Per-hour readings across the forecast window: a list of {time (ISO 8601, local), condition, temperature (Celsius), aqhi} entries.",
            ),
        ),
    ]
