# Generated by Django 5.2.13 on 2026-07-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0087_forecast_hourly_readings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecast",
            name="hourly",
            field=models.JSONField(
                default=list,
                help_text="Per-hour readings across the forecast window: a list of {time (ISO 8601, local), condition, temperature (Celsius), aqhi} entries. aqhi is null when air quality data was not yet available for that hour.",
            ),
        ),
    ]
