# Generated by Django 5.2.13 on 2026-07-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0091_alter_forecast_hourly"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="archival_reason",
            field=models.TextField(blank=True, help_text="Reason for archival."),
        ),
    ]
