# Generated by Django 5.2.13 on 2026-08-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0092_event_archival_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="previous_ends_at",
            field=models.DateTimeField(
                blank=True,
                help_text="End time of the event before the latest reschedule.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="previous_starts_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Start time of the event before the latest reschedule.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="reschedule_reason",
            field=models.TextField(
                blank=True, help_text="Reason for the latest reschedule."
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="rescheduled_at",
            field=models.DateTimeField(
                blank=True, help_text="When the event was last rescheduled.", null=True
            ),
        ),
    ]
