# Generated by Django 5.2.13 on 2026-08-01 12:09

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0092_event_archival_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changed_fields",
                    models.JSONField(
                        help_text="Names of the registration fields this amendment changed."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                (
                    "ride_leader_preference",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No"), ("na", "N/A")],
                        default="na",
                        max_length=2,
                    ),
                ),
                (
                    "first_time_attendee",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No"), ("na", "N/A")],
                        default="na",
                        max_length=2,
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_amendments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="backoffice.registration",
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="backoffice.ride",
                    ),
                ),
                (
                    "speed_range_preference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="backoffice.speedrange",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["registration", "-created_at"],
                        name="backoffice__registr_fc67ee_idx",
                    )
                ],
            },
        ),
    ]
