# Generated by Django 5.2.13 on 2026-08-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0093_registrationsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="unconfirmed_alert_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When staff were alerted that this registration had not been confirmed.",
                null=True,
            ),
        ),
    ]
