# Generated by Django 5.2.13 on 2026-08-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0094_event_previous_ends_at_event_previous_starts_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='last_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
