# Generated by Django 5.2.13 on 2026-08-02 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0094_event_previous_ends_at_event_previous_starts_at_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "registration_verification_reminder",
                                "Registration verification reminder",
                            ),
                            (
                                "staff_unconfirmed_digest",
                                "Staff unconfirmed registration digest",
                            ),
                        ],
                        help_text="Which notification was sent.",
                        max_length=64,
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        help_text="Email addresses the notification was sent to."
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("target_repr", models.CharField(blank=True, max_length=255)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["target_content_type", "target_object_id"],
                        name="backoffice__target__b4bba8_idx",
                    ),
                    models.Index(fields=["kind"], name="backoffice__kind_bc2fa6_idx"),
                    models.Index(
                        fields=["sent_at"], name="backoffice__sent_at_267af0_idx"
                    ),
                ],
            },
        ),
    ]
