# Generated by Django 5.2.13 on 2026-08-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0094_event_previous_ends_at_event_previous_starts_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ask_prospective_member',
            field=models.BooleanField(default=False, help_text='Check if you want to ask registrants whether they are not yet an OBC member.'),
        ),
        migrations.AddField(
            model_name='registration',
            name='prospective_member',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('na', 'N/A')], default='na', max_length=2),
        ),
        migrations.AddField(
            model_name='registrationsnapshot',
            name='prospective_member',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('na', 'N/A')], default='na', max_length=2),
        ),
    ]
