# Generated by Django 5.2.10 on 2026-07-04 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditevent',
            name='audit_audit_content_c1f818_idx',
        ),
        migrations.RenameField(
            model_name='auditevent',
            old_name='content_type',
            new_name='target_content_type',
        ),
        migrations.RenameField(
            model_name='auditevent',
            old_name='object_id',
            new_name='target_object_id',
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='audit_audit_target__1e9cda_idx'),
        ),
    ]
