# Generated by Django 5.2.10 on 2026-07-04 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_rename_target_fields'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditevent',
            name='audit_audit_subject_201c71_idx',
        ),
        migrations.RenameField(
            model_name='auditevent',
            old_name='subject',
            new_name='actor',
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor'], name='audit_audit_actor_i_40b234_idx'),
        ),
    ]
