# Generated by Django 5.2.10 on 2026-07-01 14:03

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL path segment, e.g. "user-guide".', unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', markdownx.models.MarkdownxField(help_text='Markdown content. Cross-link other pages with relative links, e.g. [User Guide](/pages/user-guide).')),
                ('published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
